export const GET_TRANSACTION = "GET_TRANSACTION"
export const GET_TRANSACTION_ERROR = "GET_TRANSACTION_ERROR"

export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const ADD_TRANSACTION_ERROR = "ADD_TRANSACTION_ERROR"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const UPDATE_TRANSACTION_ERROR = "UPDATE_TRANSACTION_ERROR"

export const DELETE_TRANSACTION = "DELETE_TRANSACTION"
export const DELETE_TRANSACTION_ERROR = "DELETE_TRANSACTION_ERROR"
