export const GET_USER = "GET_USER"
export const GET_USER_ERROR = "GET_USER_ERROR"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const SIGNIN_USER = "SIGNIN_USER"
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR"

export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"

export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"

export const USER_SIGNOUT = "USER_SIGNOUT"